# Generated by Django 6.0.6 on 2026-08-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanExpertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_index', models.PositiveIntegerField()),
                ('article_text', models.TextField()),
                ('selected_label', models.IntegerField(choices=[(0, 'World'), (1, 'Sports'), (2, 'Business'), (3, 'Sci/Tech')])),
                ('true_label', models.IntegerField(choices=[(0, 'World'), (1, 'Sports'), (2, 'Business'), (3, 'Sci/Tech')])),
                ('is_correct', models.BooleanField()),
                ('query_strategy', models.CharField(default='Human Expert Demo', max_length=100)),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
