# Generated by Django 6.0.6 on 2026-08-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanexpertresponse',
            name='classifier_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='humanexpertresponse',
            name='classifier_entropy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='humanexpertresponse',
            name='classifier_prediction',
            field=models.IntegerField(blank=True, choices=[(0, 'World'), (1, 'Sports'), (2, 'Business'), (3, 'Sci/Tech')], null=True),
        ),
        migrations.AlterField(
            model_name='humanexpertresponse',
            name='query_strategy',
            field=models.CharField(max_length=100),
        ),
    ]
